// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoloAdventureAPI.Context;

#nullable disable

namespace SoloAdventureAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221125191530_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SoloAdventureAPI.Models.Aventura", b =>
                {
                    b.Property<int>("AventuraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("AventuraAtiva")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 11, 25, 16, 15, 30, 231, DateTimeKind.Local).AddTicks(8530));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AventuraId");

                    b.ToTable("Aventuras", (string)null);
                });

            modelBuilder.Entity("SoloAdventureAPI.Models.OrigemDestino", b =>
                {
                    b.Property<int>("PassoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("PassoDestinoId")
                        .HasColumnType("int");

                    b.HasKey("PassoOrigemId", "PassoDestinoId");

                    b.HasIndex("PassoDestinoId");

                    b.ToTable("OrigensDestinos", (string)null);
                });

            modelBuilder.Entity("SoloAdventureAPI.Models.Passo", b =>
                {
                    b.Property<int>("PassoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AventuraId")
                        .HasColumnType("int");

                    b.Property<bool>("Inicio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PassoAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.HasKey("PassoId");

                    b.HasIndex("AventuraId");

                    b.ToTable("Passos", (string)null);
                });

            modelBuilder.Entity("SoloAdventureAPI.Models.OrigemDestino", b =>
                {
                    b.HasOne("SoloAdventureAPI.Models.Passo", "PassoDestino")
                        .WithMany("Destinos")
                        .HasForeignKey("PassoDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloAdventureAPI.Models.Passo", "PassoOrigem")
                        .WithMany("Origens")
                        .HasForeignKey("PassoOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassoDestino");

                    b.Navigation("PassoOrigem");
                });

            modelBuilder.Entity("SoloAdventureAPI.Models.Passo", b =>
                {
                    b.HasOne("SoloAdventureAPI.Models.Aventura", "Aventura")
                        .WithMany("Passos")
                        .HasForeignKey("AventuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aventura");
                });

            modelBuilder.Entity("SoloAdventureAPI.Models.Aventura", b =>
                {
                    b.Navigation("Passos");
                });

            modelBuilder.Entity("SoloAdventureAPI.Models.Passo", b =>
                {
                    b.Navigation("Destinos");

                    b.Navigation("Origens");
                });
#pragma warning restore 612, 618
        }
    }
}
